# Generated by Django 5.0.6 on 2024-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_chatroom_created_at_chatroom_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms_images/'),
        ),
    ]
